authToken = "ACCESS_TOKEN"
spreadsheetId = "SPEADSHEET_ID"
sheetName = "SHEET_NUMBER"
dataRange = "A2:C"
templatePath = "TEMPLATE_PATH"
certificateUrlColumnIndex = 2
emailColumnIndex = 1
nameColumnNumber = 0